pull_request_rules:
    - name: Automatic merge of development dependencies update
      conditions:
          - base=develop
          - author=dependabot-preview[bot]
          - title~=build(deps-dev)*
          - status-success~=LGTM analysis
        #   - status-success=Travis CI - Branch
        #   - status-success=Travis CI - Pull Request
        #   - status-success=codecov/patch
        #   - status-success=codecov/project
          - status-success~=security/snyk
      actions:
          merge:
              strict: true
    - name: delete head branch after merge
      conditions: []
      actions:
          delete_head_branch: {}
